version: '3.7'

services:
  #sample-prod:
  #  container_name: sample-prod
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - '1337:80'
  #  restart: always
  #  networks:
  #    - network_mobilis

  bucardo:
    # image: jefftian/bucardo
    build:
      context: .docker/bucardo
      dockerfile: Dockerfile
    container_name: bucardo-mobilis
    restart: always
    ports:
      - '5433:5432'
    networks:
      - network_mobilis
    volumes:
      - .docker/bucardo:/media/bucardo

networks:
  network_mobilis:
    name: network_mobilis
