version: '3.7'

services:
  sample-prod:
    container_name: sample-prod
    build:
      context: .
      dockerfile: .docker/raspberry/Dockerfile
    ports:
      - '1337:80'
    restart: always
    networks:
      - network_mobilis

networks:
  network_mobilis:
    name: network_mobilis
